### ISSUE TITLE
 Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules     at HTMLLinkElement.s

### ISSUE THREAD

**Issue by wwq146213** [yushulx/Scan-Documents-with-Node.JS#7]
![image](https://github.com/yushulx/Scan-Documents-with-Node.JS/assets/93062479/061baf0b-10ba-4e41-984d-8b99507848b5)
打开之后报错了

**Comment by yushulx** [comment]
@wwq146213 the issue has been fixed in DWT [v18.2.1](https://www.npmjs.com/package/dwt/v/18.2.1).
